#!/usr/bin/env python3
"""Scores labelled exercise clips with the Python port of Cindy's production pipeline.

It runs the production counting rules over decoded video frames with two engines — one checking
setup, one scoring the whole labelled clip — and records the diagnostics behind every rejection,
so a counting bug can be reproduced and iterated on in seconds rather than on a device.

The port is kept honest by tools/video_regression/parity_check.py, which diffs it frame by frame
against a trace generated by the production Kotlin. Run that before trusting a verdict here.

    python3 tools/video_regression/run_batch.py --scenarios tests/scenarios/local_regressions.json
    python3 tools/video_regression/run_batch.py --video clip.mp4 --exercise squat --expect 15
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cindy_sim.pose_detector import PoseDetector
from cindy_sim.tracking_health import TrackingHealth, TrackingHealthMonitor
from cindy_sim.workout_engine import (
    CindyProfile, Exercise, PullVariant, RepEvent, SetupStage, WorkoutEngine,
)

ROOT = Path(__file__).resolve().parents[2]
#: Read noise of a phone sensor at base gain, in 8-bit counts. Conservative.
READ_NOISE = 2.0
#: Ceiling on how far a camera will push its own gain to hold the brightness up.
ISO_CAP = 12.0

EXERCISES = {
    "pullup": Exercise.PULLUP, "pull-up": Exercise.PULLUP,
    "pullups": Exercise.PULLUP, "pull-ups": Exercise.PULLUP,
    "pushup": Exercise.PUSHUP, "push-up": Exercise.PUSHUP,
    "pushups": Exercise.PUSHUP, "push-ups": Exercise.PUSHUP,
    "squat": Exercise.SQUAT, "squats": Exercise.SQUAT,
}
# Selects the movement variant a pull-up clip is scored under. Only the pull-up gate actually
# branches on the profile today (the relaxed dead-hang rule for an assisted athlete); push-up and
# squat variants count identically to their strict counterparts, so no equivalent map exists for
# them yet -- see KneePushupTest for why.
PULL_VARIANTS = {
    "strict": PullVariant.STRICT_PULL_UP,
    "strict_pull_up": PullVariant.STRICT_PULL_UP,
    "band_assisted": PullVariant.BAND_ASSISTED_PULL_UP,
    "band_assisted_pull_up": PullVariant.BAND_ASSISTED_PULL_UP,
}
MODELS = {
    None: "movenet_thunder.tflite",
    "thunder": "movenet_thunder.tflite",
    "movenet_thunder.tflite": "movenet_thunder.tflite",
    "lightning": "movenet_lightning.tflite",
    "movenet_lightning.tflite": "movenet_lightning.tflite",
}


@dataclass
class InferredFrame:
    timestamp_ms: int
    width: int
    height: int
    tracking_stable: bool
    keypoints: list
    #: What the detector had to brighten this crop by; 1.0 means it needed no help.
    soft_gain: float = 1.0


@dataclass
class ScenarioReport:
    id: str
    exercise: str
    expected_reps: int
    observed_reps: int
    setup: str | None
    count_times: list[int]
    frames: list[dict]
    failures: list[str]
    tags: list[str] = field(default_factory=list)
    tolerance: int = 0
    #: Worst tracking health the monitor reported over the clip, and the time it spent lost.
    worst_health: str = "GOOD"
    lost_ms: int = 0
    #: Cindy mode only (`run_cindy_scenario`): {"pullup"/"pushup"/"squat": {"expected", "observed",
    #: "eventsMs"}}. Empty for every fixed-exercise scenario -- `expected_reps`/`observed_reps`
    #: above stay the single number those scenarios have always reported.
    per_movement: dict = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not self.failures

    @property
    def signed_error(self) -> int:
        return self.observed_reps - self.expected_reps

    @property
    def within_tolerance(self) -> bool:
        return abs(self.signed_error) <= self.tolerance

    @property
    def first_count_ms(self) -> int | None:
        return self.count_times[0] if self.count_times else None

    @property
    def rejections_by_gate(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for frame in self.frames:
            key = frame["rejection"] or "(scored/none)"
            counts[key] = counts.get(key, 0) + 1
        return dict(sorted(counts.items(), key=lambda kv: -kv[1]))

    @property
    def category(self) -> str:
        """Valid and deliberately-invalid clips must never be averaged into one number."""
        if self.expected_reps == 0:
            return "must-not-count"
        for tag in ("occlusion", "camera-cut", "known-gap"):
            if tag in self.tags:
                return "difficult-but-valid"
        return "clean-valid"


def dim(frame: np.ndarray, light: dict, rng) -> np.ndarray:
    """Applies a low-light model to one frame, so a fixture can describe the conditions it tests.

    The point is to reproduce a failure nobody recorded. A tester lost pull-up tracking around the
    tenth round of a Cindy at sunset, and with no footage of it the only honest way to work on the
    problem was to take clips whose correct score is known and take the light away.

    Two models, because a phone does not sit still while the sun goes down:

    ``uncompensated``
        ``out = frame * gain``. The exposure is already at its limit, so less light simply means a
        darker picture. Also what happens at *any* light level when auto-exposure meters on a
        bright background and leaves the subject underexposed.

    ``iso``
        ``out = frame * gain * iso + noise(sigma * iso)``. What the camera does first: raise gain
        to hold the brightness up, amplifying read noise with it. The picture stays bright and
        gets dirty -- and this is the regime nothing in software can rescue, which is exactly why
        it is worth having a fixture for.
    """
    gain = float(light.get("gain", 1.0))
    model = str(light.get("model", "uncompensated"))
    f = frame.astype(np.float32)
    if model == "iso":
        iso = min(1.0 / max(gain, 1e-6), ISO_CAP)
        out = f * gain * iso
        out = out + rng.normal(0.0, READ_NOISE * iso, size=f.shape).astype(np.float32)
    else:
        out = f * gain
    return np.clip(out, 0, 255).astype(np.uint8)


def infer_video(
    path: Path, model_asset: str, errors: list[str], light: dict | None = None
) -> list[InferredFrame]:
    """Decodes every frame and runs the production MoveNet crop/track pipeline over it."""
    capture = cv2.VideoCapture(str(path))
    if not capture.isOpened():
        errors.append(f"cannot open video: {path}")
        return []
    fps = capture.get(cv2.CAP_PROP_FPS)
    if not fps or fps <= 0:
        errors.append(f"video has no usable FPS metadata: {path}")
        capture.release()
        return []

    detector = PoseDetector(str(ROOT / "app/src/main/assets" / model_asset), model_asset)
    frames: list[InferredFrame] = []
    index = 0
    # Seeded, so a fixture that adds sensor noise still fails and passes for the same reasons.
    rng = np.random.default_rng(7) if light else None
    try:
        while True:
            ok, bgr = capture.read()
            if not ok:
                break
            rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
            if light:
                rgb = dim(rgb, light, rng)
            # The Android runner reads `detector.tracking` before calling detect(), so the flag it
            # feeds the engine describes the *previous* frame. Replicated deliberately: the point
            # of this harness is to reproduce the phone, quirks included.
            tracking = detector.tracking
            frames.append(
                InferredFrame(
                    timestamp_ms=int(index * 1000.0 / fps),
                    width=rgb.shape[1],
                    height=rgb.shape[0],
                    tracking_stable=tracking,
                    keypoints=detector.detect(rgb),
                    soft_gain=detector.soft_gain,
                )
            )
            index += 1
    finally:
        capture.release()
        detector.close()
    return frames


def configure_manual_bar(engine: WorkoutEngine, scenario: dict, first: InferredFrame) -> None:
    bar = scenario.get("bar")
    if not bar or str(bar.get("mode", "auto")).lower() != "manual":
        return
    engine.configure_manual_bar(
        y_normalized=float(bar["yNormalized"]),
        x_min_normalized=float(bar["xMinNormalized"]),
        x_max_normalized=float(bar["xMaxNormalized"]),
        frame_width=first.width,
        frame_height=first.height,
    )


def check_setup(expected: str | None, actual: SetupStage | None, errors: list[str]) -> None:
    if expected is None:
        return
    key = expected.lower()
    accepted = {
        "valid": actual in (SetupStage.MOVING, SetupStage.READY),
        "ready": actual is SetupStage.READY,
        "framing": actual is SetupStage.FRAMING,
        "invalid": actual is SetupStage.FRAMING,
        "poor": actual is SetupStage.POOR,
        "paused": actual is SetupStage.POOR,
    }
    if key not in accepted:
        errors.append(f"unsupported expectedSetup '{expected}'")
        return
    if not accepted[key]:
        name = actual.name.lower() if actual else "none"
        errors.append(f"expected setup '{expected}', observed '{name}'")


def check_events(scenario: dict, observed: list[int], errors: list[str]) -> None:
    expected = scenario.get("expectedRepEventsMs") or []
    if not expected:
        return
    tolerance = int(scenario.get("eventToleranceMs", 500))
    if len(expected) != len(observed):
        errors.append(f"expected {len(expected)} count events, observed {len(observed)}")
        return
    for i, (want, got) in enumerate(zip(expected, observed), start=1):
        if abs(want - got) > tolerance:
            errors.append(f"event {i}: expected about {want}ms, observed {got}ms")


def run_scenario(scenario: dict) -> ScenarioReport:
    errors: list[str] = []
    name = scenario.get("exercise", "").lower()
    if name not in EXERCISES:
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], [f"unsupported exercise '{name}'"])
    exercise = EXERCISES[name]

    pull_key = (scenario.get("pull") or "").lower() or None
    if pull_key is not None and pull_key not in PULL_VARIANTS:
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], [f"unsupported pull variant '{scenario.get('pull')}'"])
    profile = CindyProfile(pull=PULL_VARIANTS[pull_key]) if pull_key else CindyProfile()

    model = MODELS.get((scenario.get("model") or "").lower() or None)
    if model is None:
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], [f"unsupported model '{scenario.get('model')}'"])

    video = Path(scenario["video"])
    if not video.is_absolute():
        video = ROOT / video
    if not video.is_file():
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], [f"missing fixture: {video}"])

    # A scenario may describe the light it is testing under, which is how a failure nobody
    # recorded gets a regression fixture at all.
    inferred = infer_video(video, model, errors, scenario.get("light"))
    if not inferred:
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], errors)

    # Setup is validated separately from the score. Dataset labels normally include every
    # movement in a clip, while the phone deliberately does not score its two setup reps, so a
    # scoring engine sees the complete clip and a second engine verifies framing/calibration.
    setup_engine = WorkoutEngine(fixed_exercise=exercise, profile=profile)
    setup_engine.begin_setup()
    configure_manual_bar(setup_engine, scenario, inferred[0])
    setup = None
    for frame in inferred:
        before = setup_engine.reps
        blocked = setup_engine.on_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
        if blocked is not RepEvent.NONE or setup_engine.reps != before:
            errors.append(f"workout count changed before setup completed at {frame.timestamp_ms}ms")
        setup = setup_engine.on_setup_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
    check_setup(scenario.get("expectedSetup"), setup.stage if setup else None, errors)

    engine = WorkoutEngine(fixed_exercise=exercise, profile=profile)
    configure_manual_bar(engine, scenario, inferred[0])
    health = TrackingHealthMonitor()
    worst = TrackingHealth.GOOD
    frames: list[dict] = []
    count_times: list[int] = []
    for frame in inferred:
        event = engine.on_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
        d = engine.diagnostics
        health.update(engine.exercise, d.pose_legible, frame.soft_gain, frame.timestamp_ms)
        if health.health is TrackingHealth.LOST or (
            health.health is TrackingHealth.WEAK and worst is TrackingHealth.GOOD
        ):
            worst = health.health
        if event is not RepEvent.NONE:
            count_times.append(frame.timestamp_ms)
            if not d.scoring_confidence_adequate:
                errors.append(f"count at {frame.timestamp_ms}ms with inadequate confidence")
            if exercise is Exercise.PULLUP:
                if not d.identity_stable:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms without stable identity")
                if not d.bar_gate_open:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms outside bar zone")
                if not d.dead_hang_since_last_rep or not d.reset_below_bar_seen:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms without a fresh reset dead hang")
                if not d.head_above_bar:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms before head crossed bar")
        frames.append({
            "timestampMs": frame.timestamp_ms,
            "event": event.name,
            "count": engine.reps,
            "state": engine.counting_state,
            "signal": round(engine.signal, 3) if engine.signal == engine.signal else None,
            "learnedRange": round(engine.learned_range, 3),
            "minimumConfidence": round(d.minimum_confidence, 4),
            "confidenceAdequate": d.scoring_confidence_adequate,
            "barGateOpen": d.bar_gate_open,
            "headAboveBar": d.head_above_bar,
            "resetSeen": d.reset_below_bar_seen,
            "rejection": d.rejection_reason,
            "poseLegible": d.pose_legible,
            "softGain": round(frame.soft_gain, 3),
            "health": health.health.name,
        })

    expected_reps = int(scenario.get("expectedReps", 0))
    tolerance = int(scenario.get("countTolerance", 0))
    # A tolerance is an evaluation policy, not a lowered expectation: the signed error against
    # ground truth is reported regardless of whether the scenario passes.
    if abs(engine.reps - expected_reps) > tolerance:
        suffix = f" (tolerance {tolerance})" if tolerance else ""
        errors.append(f"expected {expected_reps} reps, observed {engine.reps}{suffix}")
    wanted_state = scenario.get("expectedCountingState")
    if wanted_state and engine.counting_state != wanted_state.lower():
        errors.append(f"expected final state '{wanted_state}', observed '{engine.counting_state}'")
    check_events(scenario, count_times, errors)

    # A fixture may assert what the *monitor* was supposed to notice, not only what was counted.
    # That is the half of this feature a rep count cannot test: the failure it exists for is one
    # where the score looks plausible and is quietly wrong.
    wanted_health = scenario.get("expectedTracking")
    if wanted_health and worst.name != wanted_health.upper():
        errors.append(f"expected tracking to reach {wanted_health.upper()}, observed {worst.name}")

    return ScenarioReport(
        id=scenario["id"], exercise=name, expected_reps=expected_reps, observed_reps=engine.reps,
        setup=setup.stage.name.lower() if setup else None, count_times=count_times,
        frames=frames, failures=errors, tags=scenario.get("tags", []), tolerance=tolerance,
        worst_health=worst.name, lost_ms=health.lost_ms,
    )


#: Exercise enum members to the scenario-file movement names `run_cindy_scenario` reports
#: per-movement counts under. The reverse of `EXERCISES`' pullup/pushup/squat aliases.
MOVEMENT_NAME = {Exercise.PULLUP: "pullup", Exercise.PUSHUP: "pushup", Exercise.SQUAT: "squat"}


def run_cindy_scenario(scenario: dict) -> ScenarioReport:
    """Scores a full, no-fixed-exercise Cindy attempt: setup until READY, then the real
    progression through pull-ups, push-ups and squats, in `MainActivity.analyse`'s order --
    `on_setup_frame` every frame while SETUP, `finish_setup()` the moment it reports READY, and
    `on_frame` for every frame after that (never both for the same frame, matching the app: a
    frame is SETUP xor RUNNING, and the switch happens between frames, on `applySetup`'s callback).

    Unlike the fixed-exercise path above, there is no second "scoring" engine that skips setup
    entirely: Cindy mode *is* the setup behaviour under test, calibration reps and all. The first
    two pull-ups the athlete performs are consumed by calibration exactly as they are on the phone
    -- counted toward `RepCounter`'s learned band, then zeroed by `finish_setup()`'s
    `reset_count()` before the clock starts, per `WorkoutEngine.on_setup_frame`/`finish_setup`. So
    `expectedRepsByMovement["pullup"]` must be the label's *total* pull-up count including those
    two; `per_movement["pullup"]["observed"]` only ever reflects what happened after calibration,
    same as the app's own scoreboard.

    Two optional scenario fields reproduce the athlete's own controls, for footage the counter
    cannot calibrate or progress on by itself:

    - ``"setup": "skip"`` -- the SKIP button: no calibration, every frame goes to `on_frame`, and
      the calibration pull-ups count like any other. The label then equals the expected count.
    - ``"skipTo": [{"atMs": 25000, "movement": "pushup"}, ...]`` -- the athlete tapping "skip" when
      the app has not moved on by itself: at `atMs`, if the engine is still on an earlier movement,
      `skip_exercise()` banks what was done and advances until it reaches `movement`. A movement
      the engine already reached on its own is left alone, so a correct count is never skipped.
    """
    errors: list[str] = []
    video = Path(scenario["video"])
    if not video.is_absolute():
        video = ROOT / video
    if not video.is_file():
        return ScenarioReport(scenario["id"], "cindy", 0, 0, None, [], [], [f"missing fixture: {video}"])

    model = MODELS.get((scenario.get("model") or "").lower() or None)
    if model is None:
        return ScenarioReport(scenario["id"], "cindy", 0, 0, None, [], [],
                              [f"unsupported model '{scenario.get('model')}'"])

    inferred = infer_video(video, model, errors, scenario.get("light"))
    if not inferred:
        return ScenarioReport(scenario["id"], "cindy", 0, 0, None, [], [], errors)

    engine = WorkoutEngine()  # fixed_exercise=None: the real pull-up -> push-up -> squat -> ... loop
    skip_setup = (scenario.get("setup") or "").lower() == "skip"
    if not skip_setup:
        engine.begin_setup()
    order = list(MOVEMENT_NAME)
    skips = sorted(
        ((int(s["atMs"]), EXERCISES[s["movement"]]) for s in scenario.get("skipTo", [])),
        key=lambda s: s[0],
    )
    configure_manual_bar(engine, scenario, inferred[0])
    health = TrackingHealthMonitor()
    worst = TrackingHealth.GOOD

    running = skip_setup
    setup_result = None
    frames: list[dict] = []
    count_times: list[int] = []
    per_movement_counts = {name: 0 for name in MOVEMENT_NAME.values()}
    per_movement_events: dict[str, list[int]] = {name: [] for name in MOVEMENT_NAME.values()}

    for frame in inferred:
        if not running:
            setup_result = engine.on_setup_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
            if setup_result.stage is SetupStage.READY:
                engine.finish_setup()
                running = True
            continue  # this frame was SETUP; the app never also calls onFrame for it

        while skips and frame.timestamp_ms >= skips[0][0]:
            _, target = skips.pop(0)
            while order.index(engine.exercise) < order.index(target):
                engine.skip_exercise()

        event = engine.on_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
        d = engine.diagnostics
        health.update(engine.exercise, d.pose_legible, frame.soft_gain, frame.timestamp_ms)
        if health.health is TrackingHealth.LOST or (
            health.health is TrackingHealth.WEAK and worst is TrackingHealth.GOOD
        ):
            worst = health.health

        if event in (RepEvent.REP, RepEvent.EXERCISE_DONE, RepEvent.ROUND_DONE):
            # A plain REP leaves `engine.exercise` on the movement that just scored. An
            # EXERCISE_DONE/ROUND_DONE has already advanced it (WorkoutEngine._advance banks the
            # rep under the old exercise before reassigning), so the movement that just finished
            # is the *previous* one.
            finished = engine.exercise if event is RepEvent.REP else engine.exercise.previous()
            name = MOVEMENT_NAME[finished]
            per_movement_counts[name] += 1
            per_movement_events[name].append(frame.timestamp_ms)
            count_times.append(frame.timestamp_ms)

        frames.append({
            "timestampMs": frame.timestamp_ms, "event": event.name, "exercise": engine.exercise.label,
            "count": engine.reps, "state": engine.counting_state,
            "signal": round(engine.signal, 3) if engine.signal == engine.signal else None,
            "rejection": d.rejection_reason, "poseLegible": d.pose_legible,
            "identityStable": d.identity_stable, "softGain": round(frame.soft_gain, 3),
            "health": health.health.name,
        })

    labelled = {k: int(v) for k, v in scenario.get("expectedRepsByMovement", {}).items()}
    for name, expected in labelled.items():
        observed = per_movement_counts.get(name, 0)
        tolerance = int(scenario.get("countTolerance", 0))
        if abs(observed - expected) > tolerance:
            errors.append(f"{name}: expected {expected} reps, observed {observed}"
                          + (f" (tolerance {tolerance})" if tolerance else ""))
    if not running:
        errors.append("setup never reached READY -- no workout frames were scored")

    check_events(scenario, count_times, errors)
    wanted_health = scenario.get("expectedTracking")
    if wanted_health and worst.name != wanted_health.upper():
        errors.append(f"expected tracking to reach {wanted_health.upper()}, observed {worst.name}")

    return ScenarioReport(
        id=scenario["id"], exercise="cindy",
        expected_reps=sum(labelled.values()), observed_reps=sum(per_movement_counts.values()),
        setup=setup_result.stage.name.lower() if setup_result else None, count_times=count_times,
        frames=frames, failures=errors, tags=scenario.get("tags", []),
        tolerance=int(scenario.get("countTolerance", 0)), worst_health=worst.name, lost_ms=health.lost_ms,
        per_movement={
            name: {"expected": labelled.get(name, 0), "observed": per_movement_counts[name],
                   "eventsMs": per_movement_events[name]}
            for name in MOVEMENT_NAME.values()
        },
    )


def score_scenario(scenario: dict) -> ScenarioReport:
    """Dispatches to the real Cindy progression (no fixed exercise) or the ordinary
    single-movement path, so every existing catalogue keeps running exactly as it did.
    """
    if (scenario.get("exercise") or "").lower() == "cindy":
        return run_cindy_scenario(scenario)
    return run_scenario(scenario)


def load_catalogues(paths: list[Path]) -> list[dict]:
    scenarios: list[dict] = []
    for path in paths:
        if not path.is_file():
            print(f"warning: no catalogue at {path}", file=sys.stderr)
            continue
        scenarios.extend(json.loads(path.read_text()).get("scenarios", []))
    return scenarios


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scenarios", type=Path, nargs="*", default=[])
    parser.add_argument("--video", type=Path, help="score a single clip without a catalogue")
    parser.add_argument("--exercise", choices=sorted(set(EXERCISES) | {"cindy"}), help="with --video")
    parser.add_argument("--expect", type=int, default=0, help="expected reps for --video")
    parser.add_argument("--pull", choices=sorted(PULL_VARIANTS), help="pull-up variant for --video")
    parser.add_argument("--report", type=Path, default=ROOT / "tests/reports/python-regression.json")
    parser.add_argument("--frames", action="store_true", help="print every scoring frame")
    args = parser.parse_args()

    if args.video:
        if not args.exercise:
            parser.error("--video requires --exercise")
        scenarios = [{
            "id": args.video.stem, "video": str(args.video), "exercise": args.exercise,
            "expectedReps": args.expect, "tags": ["ad-hoc"], "pull": args.pull,
        }]
    else:
        paths = args.scenarios or sorted((ROOT / "tests/scenarios").glob("*.json"))
        scenarios = load_catalogues(paths)

    if not scenarios:
        print("No scenarios to run. Add fixtures and labels first.", file=sys.stderr)
        return 2

    reports = [score_scenario(s) for s in scenarios]

    for report in reports:
        status = "OK" if report.ok else "FAIL"
        print(f"\nScenario: {report.id}  [{report.exercise}]")
        print(f"  Expected reps: {report.expected_reps}")
        print(f"  Counted reps:  {report.observed_reps}")
        print(f"  Signed error:  {report.signed_error:+d}"
              + (f" (tolerance ±{report.tolerance})" if report.tolerance else ""))
        print(f"  Setup:         {report.setup}")
        if report.count_times:
            print(f"  Counted at:    {', '.join(f'{t}ms' for t in report.count_times)}")
        print(f"  Status:        {status}")
        for failure in report.failures:
            print(f"    - {failure}")
        if args.frames:
            for frame in report.frames:
                print(f"    {frame['timestampMs']:>7}ms {frame['event']:<13} n={frame['count']:<3}"
                      f" {frame['state']:<5} sig={frame['signal']} rej={frame['rejection']}")

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps({"scenarios": [
        {"id": r.id, "exercise": r.exercise, "category": r.category,
         "expectedReps": r.expected_reps, "observedReps": r.observed_reps,
         "signedError": r.signed_error, "countTolerance": r.tolerance,
         "withinTolerance": r.within_tolerance, "setup": r.setup,
         "countTimestampsMs": r.count_times, "firstCountMs": r.first_count_ms,
         "rejectionsByGate": r.rejections_by_gate,
         "tags": r.tags, "failures": r.failures, "frames": r.frames}
        for r in reports
    ]}, indent=2))

    print("\n" + "=" * 62)
    print("Metrics by category — valid and must-not-count clips stay separate,")
    print("because blending them produces a flattering number that means nothing.")
    print("=" * 62)
    for category in ("clean-valid", "difficult-but-valid", "must-not-count"):
        group = [r for r in reports if r.category == category]
        if not group:
            continue
        exact = sum(1 for r in group if r.signed_error == 0)
        mae = sum(abs(r.signed_error) for r in group) / len(group)
        print(f"\n  {category}  ({len(group)} clip(s))")
        print(f"    exact count:        {exact}/{len(group)}")
        print(f"    mean absolute error: {mae:.2f} reps")
        if category == "must-not-count":
            false_positives = sum(r.observed_reps for r in group)
            print(f"    false positives:     {false_positives}"
                  + ("  <-- MUST BE ZERO" if false_positives else "  (clean)"))
        under = [r.id for r in group if r.signed_error < 0]
        over = [r.id for r in group if r.signed_error > 0]
        if under:
            print(f"    under-counting:      {', '.join(under)}")
        if over:
            print(f"    over-counting:       {', '.join(over)}")

    passed = sum(1 for r in reports if r.ok)
    print(f"\n{passed}/{len(reports)} scenario(s) passed. Report: {args.report}")
    return 0 if passed == len(reports) else 1


if __name__ == "__main__":
    raise SystemExit(main())
