#!/usr/bin/env python3
"""Scores labelled exercise clips with the Python port of Cindy's production pipeline.

It runs the production counting rules over decoded video frames with two engines — one checking
setup, one scoring the whole labelled clip — and records the diagnostics behind every rejection,
so a counting bug can be reproduced and iterated on in seconds rather than on a device.

The port is kept honest by tools/video_regression/parity_check.py, which diffs it frame by frame
against a trace generated by the production Kotlin. Run that before trusting a verdict here.

    python3 tools/video_regression/run_batch.py --scenarios tests/scenarios/local_regressions.json
    python3 tools/video_regression/run_batch.py --video clip.mp4 --exercise squat --expect 15
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

import cv2

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cindy_sim.pose_detector import PoseDetector
from cindy_sim.workout_engine import Exercise, RepEvent, SetupStage, WorkoutEngine

ROOT = Path(__file__).resolve().parents[2]
EXERCISES = {
    "pullup": Exercise.PULLUP, "pull-up": Exercise.PULLUP,
    "pullups": Exercise.PULLUP, "pull-ups": Exercise.PULLUP,
    "pushup": Exercise.PUSHUP, "push-up": Exercise.PUSHUP,
    "pushups": Exercise.PUSHUP, "push-ups": Exercise.PUSHUP,
    "squat": Exercise.SQUAT, "squats": Exercise.SQUAT,
}
MODELS = {
    None: "movenet_thunder.tflite",
    "thunder": "movenet_thunder.tflite",
    "movenet_thunder.tflite": "movenet_thunder.tflite",
    "lightning": "movenet_lightning.tflite",
    "movenet_lightning.tflite": "movenet_lightning.tflite",
}


@dataclass
class InferredFrame:
    timestamp_ms: int
    width: int
    height: int
    tracking_stable: bool
    keypoints: list


@dataclass
class ScenarioReport:
    id: str
    exercise: str
    expected_reps: int
    observed_reps: int
    setup: str | None
    count_times: list[int]
    frames: list[dict]
    failures: list[str]
    tags: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.failures


def infer_video(path: Path, model_asset: str, errors: list[str]) -> list[InferredFrame]:
    """Decodes every frame and runs the production MoveNet crop/track pipeline over it."""
    capture = cv2.VideoCapture(str(path))
    if not capture.isOpened():
        errors.append(f"cannot open video: {path}")
        return []
    fps = capture.get(cv2.CAP_PROP_FPS)
    if not fps or fps <= 0:
        errors.append(f"video has no usable FPS metadata: {path}")
        capture.release()
        return []

    detector = PoseDetector(str(ROOT / "app/src/main/assets" / model_asset), model_asset)
    frames: list[InferredFrame] = []
    index = 0
    try:
        while True:
            ok, bgr = capture.read()
            if not ok:
                break
            rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
            # The Android runner reads `detector.tracking` before calling detect(), so the flag it
            # feeds the engine describes the *previous* frame. Replicated deliberately: the point
            # of this harness is to reproduce the phone, quirks included.
            tracking = detector.tracking
            frames.append(
                InferredFrame(
                    timestamp_ms=int(index * 1000.0 / fps),
                    width=rgb.shape[1],
                    height=rgb.shape[0],
                    tracking_stable=tracking,
                    keypoints=detector.detect(rgb),
                )
            )
            index += 1
    finally:
        capture.release()
        detector.close()
    return frames


def configure_manual_bar(engine: WorkoutEngine, scenario: dict, first: InferredFrame) -> None:
    bar = scenario.get("bar")
    if not bar or str(bar.get("mode", "auto")).lower() != "manual":
        return
    engine.configure_manual_bar(
        y_normalized=float(bar["yNormalized"]),
        x_min_normalized=float(bar["xMinNormalized"]),
        x_max_normalized=float(bar["xMaxNormalized"]),
        frame_width=first.width,
        frame_height=first.height,
    )


def check_setup(expected: str | None, actual: SetupStage | None, errors: list[str]) -> None:
    if expected is None:
        return
    key = expected.lower()
    accepted = {
        "valid": actual in (SetupStage.MOVING, SetupStage.READY),
        "ready": actual is SetupStage.READY,
        "framing": actual is SetupStage.FRAMING,
        "invalid": actual is SetupStage.FRAMING,
        "poor": actual is SetupStage.POOR,
        "paused": actual is SetupStage.POOR,
    }
    if key not in accepted:
        errors.append(f"unsupported expectedSetup '{expected}'")
        return
    if not accepted[key]:
        name = actual.name.lower() if actual else "none"
        errors.append(f"expected setup '{expected}', observed '{name}'")


def check_events(scenario: dict, observed: list[int], errors: list[str]) -> None:
    expected = scenario.get("expectedRepEventsMs") or []
    if not expected:
        return
    tolerance = int(scenario.get("eventToleranceMs", 500))
    if len(expected) != len(observed):
        errors.append(f"expected {len(expected)} count events, observed {len(observed)}")
        return
    for i, (want, got) in enumerate(zip(expected, observed), start=1):
        if abs(want - got) > tolerance:
            errors.append(f"event {i}: expected about {want}ms, observed {got}ms")


def run_scenario(scenario: dict) -> ScenarioReport:
    errors: list[str] = []
    name = scenario.get("exercise", "").lower()
    if name not in EXERCISES:
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], [f"unsupported exercise '{name}'"])
    exercise = EXERCISES[name]

    model = MODELS.get((scenario.get("model") or "").lower() or None)
    if model is None:
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], [f"unsupported model '{scenario.get('model')}'"])

    video = Path(scenario["video"])
    if not video.is_absolute():
        video = ROOT / video
    if not video.is_file():
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], [f"missing fixture: {video}"])

    inferred = infer_video(video, model, errors)
    if not inferred:
        return ScenarioReport(scenario["id"], name, int(scenario.get("expectedReps", 0)), 0,
                              None, [], [], errors)

    # Setup is validated separately from the score. Dataset labels normally include every
    # movement in a clip, while the phone deliberately does not score its two setup reps, so a
    # scoring engine sees the complete clip and a second engine verifies framing/calibration.
    setup_engine = WorkoutEngine(fixed_exercise=exercise)
    setup_engine.begin_setup()
    configure_manual_bar(setup_engine, scenario, inferred[0])
    setup = None
    for frame in inferred:
        before = setup_engine.reps
        blocked = setup_engine.on_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
        if blocked is not RepEvent.NONE or setup_engine.reps != before:
            errors.append(f"workout count changed before setup completed at {frame.timestamp_ms}ms")
        setup = setup_engine.on_setup_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
    check_setup(scenario.get("expectedSetup"), setup.stage if setup else None, errors)

    engine = WorkoutEngine(fixed_exercise=exercise)
    configure_manual_bar(engine, scenario, inferred[0])
    frames: list[dict] = []
    count_times: list[int] = []
    for frame in inferred:
        event = engine.on_frame(frame.keypoints, frame.timestamp_ms, frame.tracking_stable)
        d = engine.diagnostics
        if event is not RepEvent.NONE:
            count_times.append(frame.timestamp_ms)
            if not d.scoring_confidence_adequate:
                errors.append(f"count at {frame.timestamp_ms}ms with inadequate confidence")
            if exercise is Exercise.PULLUP:
                if not d.identity_stable:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms without stable identity")
                if not d.bar_gate_open:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms outside bar zone")
                if not d.dead_hang_since_last_rep or not d.reset_below_bar_seen:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms without a fresh reset dead hang")
                if not d.head_above_bar:
                    errors.append(f"pull-up count at {frame.timestamp_ms}ms before head crossed bar")
        frames.append({
            "timestampMs": frame.timestamp_ms,
            "event": event.name,
            "count": engine.reps,
            "state": engine.counting_state,
            "signal": round(engine.signal, 3) if engine.signal == engine.signal else None,
            "learnedRange": round(engine.learned_range, 3),
            "minimumConfidence": round(d.minimum_confidence, 4),
            "confidenceAdequate": d.scoring_confidence_adequate,
            "barGateOpen": d.bar_gate_open,
            "headAboveBar": d.head_above_bar,
            "resetSeen": d.reset_below_bar_seen,
            "rejection": d.rejection_reason,
        })

    expected_reps = int(scenario.get("expectedReps", 0))
    if engine.reps != expected_reps:
        errors.append(f"expected {expected_reps} reps, observed {engine.reps}")
    wanted_state = scenario.get("expectedCountingState")
    if wanted_state and engine.counting_state != wanted_state.lower():
        errors.append(f"expected final state '{wanted_state}', observed '{engine.counting_state}'")
    check_events(scenario, count_times, errors)

    return ScenarioReport(
        id=scenario["id"], exercise=name, expected_reps=expected_reps, observed_reps=engine.reps,
        setup=setup.stage.name.lower() if setup else None, count_times=count_times,
        frames=frames, failures=errors, tags=scenario.get("tags", []),
    )


def load_catalogues(paths: list[Path]) -> list[dict]:
    scenarios: list[dict] = []
    for path in paths:
        if not path.is_file():
            print(f"warning: no catalogue at {path}", file=sys.stderr)
            continue
        scenarios.extend(json.loads(path.read_text()).get("scenarios", []))
    return scenarios


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scenarios", type=Path, nargs="*", default=[])
    parser.add_argument("--video", type=Path, help="score a single clip without a catalogue")
    parser.add_argument("--exercise", choices=sorted(set(EXERCISES)), help="with --video")
    parser.add_argument("--expect", type=int, default=0, help="expected reps for --video")
    parser.add_argument("--report", type=Path, default=ROOT / "tests/reports/python-regression.json")
    parser.add_argument("--frames", action="store_true", help="print every scoring frame")
    args = parser.parse_args()

    if args.video:
        if not args.exercise:
            parser.error("--video requires --exercise")
        scenarios = [{
            "id": args.video.stem, "video": str(args.video), "exercise": args.exercise,
            "expectedReps": args.expect, "tags": ["ad-hoc"],
        }]
    else:
        paths = args.scenarios or sorted((ROOT / "tests/scenarios").glob("*.json"))
        scenarios = load_catalogues(paths)

    if not scenarios:
        print("No scenarios to run. Add fixtures and labels first.", file=sys.stderr)
        return 2

    reports = [run_scenario(s) for s in scenarios]

    for report in reports:
        status = "OK" if report.ok else "FAIL"
        print(f"\nScenario: {report.id}  [{report.exercise}]")
        print(f"  Expected reps: {report.expected_reps}")
        print(f"  Counted reps:  {report.observed_reps}")
        print(f"  Setup:         {report.setup}")
        if report.count_times:
            print(f"  Counted at:    {', '.join(f'{t}ms' for t in report.count_times)}")
        print(f"  Status:        {status}")
        for failure in report.failures:
            print(f"    - {failure}")
        if args.frames:
            for frame in report.frames:
                print(f"    {frame['timestampMs']:>7}ms {frame['event']:<13} n={frame['count']:<3}"
                      f" {frame['state']:<5} sig={frame['signal']} rej={frame['rejection']}")

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps({"scenarios": [
        {"id": r.id, "exercise": r.exercise, "expectedReps": r.expected_reps,
         "observedReps": r.observed_reps, "setup": r.setup, "countTimestampsMs": r.count_times,
         "tags": r.tags, "failures": r.failures, "frames": r.frames}
        for r in reports
    ]}, indent=2))

    passed = sum(1 for r in reports if r.ok)
    print(f"\n{passed}/{len(reports)} scenario(s) passed. Report: {args.report}")
    return 0 if passed == len(reports) else 1


if __name__ == "__main__":
    raise SystemExit(main())
